### PR TITLE
Fix precision loss when normalizing x and y coordinates

### PR DESCRIPTION
**Pull request by PepeExpress**

### CODE REVIEW

**Comment by Chappie74** [comment]
Hey thank you for spotting this. I'm *VERY* new to C++ (basically my first project) so this ran right over my head. It was basically a copy paste of what is in the PyAutoGUI code. I do see what was causing the issue though.

I've tested your changes and it does seem to fix the issue, however, I've noticed the y-coordinate is still off by 2px
(in the example below I added 100 to both. 
image


```dart
 ElevatedButton(
      onPressed: () async {
        Point<int>? position = await _api.position();
        print('Old pos $position');
        Point<int> newPosition = Point(100 + position!.x, 100 + position.y);
        await _api.moveTo(point: newPosition);
        await Future.delayed(const Duration(seconds: 3));
        print(await _api.position());
      },
      child: const Text('test'),
    )
```

I think this should be fine. So I can merge it.

**Comment by Chappie74** [comment]
Before I go ahead with the merge, can you remove any of the changes related to the example folder from the commit please 

`flutter_auto_gui_windows/example/lib/main.dart`
`flutter_auto_gui_windows/example/pubspec.lock`
`flutter_auto_gui_windows/example/windows/flutter/generated_plugins.cmake`

And update the version in the pubspec.yaml file. To maybe something like 0.0.3

**Comment by PepeExpress** [comment]
As you noticed there were some coordinates that were not 100% accurate. What I did to improve that was to subtract 1 from the screen width and height (I saw that solution to be used in some projects) and effectively there are some good improvements. I ran a test to verify how many times there were wrong coordinates with and without the `- 1` subtraction and long story short with `- 1` we had very good results. First image is a test without the `- 1`:
size
Second image is a test with `- 1`:
size-1

This test is probably not 100% accurate but totally convinced me to keep the `- 1`

**Comment by Chappie74** [comment]
Perfect! I think we can work with this.  I'll merge and update the package on pub.dev later this evening.

**Pull request merged**
